### ISSUE TITLE
Conflicting with GMT.jl package

### ISSUE THREAD

**Issue by Leon6j** [Alexander-Barth/NCDatasets.jl#147]
According to the error message, the reason seems to be “**Incompatible library version: libgdal.29.dylib requires version 202.0.0 or later, but libhdf5.200.dylib provides version 201.0.0**”.

Please see this thread for more details: https://discourse.julialang.org/t/does-the-gmt-jl-package-conflict-with-the-mat-jl-and-ncdatasets-jl-packages/70639/6

**Comment by Alexander-Barth** [comment]
In the past, julia used compiled C libraries from various different sources (Conda, Linux system package manager,  WinRPM, Homebrew,...). However, there have been many problem like these (e.g. https://discourse.julialang.org/t/problem-with-using-images/18713) where different compiled libraries are not compatible with each other (because they require a different version of zlib, libhdf5, ...). The solution for this problem is Julia's BinaryBuilder and Yggdrasil where the libraries are compiled centrally and ensuring that all libraries are compiled with the same version of dependencies.
Many Julia package have now migrated to this build system. NCDatasets did so in version 0.11.0 (https://github.com/Alexander-Barth/NCDatasets.jl/commit/937e6c305c6f393c8e2e6ea0e66f8c467f3604c6 ). 
However, it seems that has not jet been done for GMT because of the issues described [here](https://discourse.julialang.org/t/does-the-gmt-jl-package-conflict-with-the-mat-jl-and-ncdatasets-jl-packages/70639/12).
