### ISSUE TITLE
windows, ERROR: could not load symbol "nc_open"

### ISSUE THREAD

**Issue by verseve** [Alexander-Barth/NCDatasets.jl#158]
Using NCDatasets (v0.11.9) on Windows (Julia v1.6.5) the following error is thrown when loading a NetCDF file:

```julia
nc = NCDataset(path)
```

ERROR: could not load symbol "nc_open":
The specified procedure could not be found.

This happens with NetCDF_jll version v400.802.101+0 (`Pkg.add("NCDatasets")`). When using NetCDF_jll v400.702.400+0 loading of the NetCDF file works fine.

**Comment by Alexander-Barth** [comment]
Yes, this is a known issue of  NetCDF_jll. Have look here: https://github.com/JuliaPackaging/Yggdrasil/issues/3731
Therefore the release 400.802.101+0 was "yanked" from the registry and is not installed automatically.
I will close the issue here to keep the troubleshooting at one place. If somebody using Windows could contribute, that would be very welcome.
The upstream issue:
https://github.com/Unidata/netcdf-c/issues/2124

**Comment by Alexander-Barth** [comment]
See also:

https://github.com/JuliaRegistries/General/pull/53580
https://github.com/JuliaRegistries/General/pull/46656
