### ISSUE TITLE
DateTime support

### ISSUE THREAD

**Issue by gvali** [Alexander-Barth/NCDatasets.jl#2]
Now some "real" bug in my mind:

cannot write time values as floats when time attributes (units = "seconds since _some_refdate_" ) are set - the output is automatically converted to DateTime object and I get an error if I try to set variable "time" value in output:
"ERROR: LoadError: MethodError: no method matching ndims(::DateTime)"

It is not possible to set the value neither with DateTime object nor with float.

If I do not set the time attributes in outputfile, then I can at least write float-typed values in the outputfile.

I have attached one test file and script.
[test_002.zip](https://github.com/Alexander-Barth/NCDatasets.jl/files/1348178/test_002.zip)

**Comment by Alexander-Barth** [comment]
Indeed, write a variable as DateTime object (line `timevar[1]=timein[1]`) should was worked.
This is a bug which is now fixed.
I also now implemented,
```
timevar[1]=Float64(0.0);
```
because I think that many people coming from matlab would assume that this works. But I am not sure, if this would not create too much confusion (when reading a variables returns a different type than what was written to it).

**Comment by gvali** [comment]
Thanks, the script is now working! I really like the idea that I can write directly DateTime object to netCDF - this is not possible in Python. In addition, I like that I get automatically time as DateTime object.

One minor thing there is still: the missing values are not kept in my mind. In my previous test lines:
tempvar[:,:,1]=dsin["temp"][:,:,1,1];
saltvar[:,:,1]=dsin["salt"][:,:,1,1];
work, but in the output, the missing values from input file, are replaced with or filled with value 0. I guess it would be nice if the value "NA" from input is kept in output.

Sorry for bringing out some minor stuff - the package is really-really great and I am very grateful that you have implemented the changes so quickly!

**Comment by Alexander-Barth** [comment]
Thanks for confirming that it works! Do not hesitate to file future issues if you find bugs or any other weired behavior.

Concerning the last issue (the NAs replaced with zeros), I tried to reproduce this error but this code actually works. 

```
using NCDatasets
using DataArrays
x = DataArray([1,2,3,4],[false,false,false,true])

# prepare test data
ds = Dataset("input.nc","c");
defDim(ds,"dim",length(x))
v = defVar(ds,"var",Float64,("dim",))
v.attrib["_FillValue"] = 100.
v[:] = x
close(ds)

# copy one variable
ds = Dataset("input.nc");
dsout = Dataset("output.nc","c");
defDim(dsout,"dim",length(x))
vout = defVar(dsout,"var",Float64,("dim",))
# if this line is commented then the 4th value of var is an
# undefined float (sometimes zero or sometimes seemingly random)
vout.attrib["_FillValue"] = 200.
vout[:] = ds["var"][:]

close(ds)
close(dsout)
```
`ncdump output.nc` gives the following output:

```
netcdf output {
dimensions:
	dim = 4 ;
variables:
	double var(dim) ;
		var:_FillValue = 200. ;
data:

 var = 1, 2, 3, _ ;
}
```

But the snippet fails in a similar way that you are describing if I omit the `FillValue_` attribute of `vout`.
Did you set the `FillValue_` attributes of the output variable? If this is not the problem, can you send me a script that reproduces this error ?

Thanks a lot!

**Comment by gvali** [comment]
I get following error, when I try to set the "_FillValue":
ERROR: LoadError: NCDatasets.NetCDFError(-45, "NetCDF: Not a valid data type or _FillValue type mismatch")

I can set attribute "missing_value", but as you already said in your script comment: the values are filled with value 0 or close to 0. This is what I see with "ncview", when I open my output file.

I have again attached my test. 
[test_003.zip](https://github.com/Alexander-Barth/NCDatasets.jl/files/1351498/test_003.zip)

**Comment by Alexander-Barth** [comment]
In fact, fill values must be of the same type as the NetCDF variable. So in your case the following works:
```julia
tempvar.attrib["_FillValue"]=Float32(-9999.);
```
I was a bit confused by your script because there is a lot of thinks going on at the same time. I think that there is also a problem at line 61:
```
	timevar[1]=timein[1]
```
In fact `timevar` is a variable from the dataset `ds` which you close at line 54.

If you see any future error or bugs, you to not need to bother to catch the error. Without the catch block, I see the stack-trace with line numbers which is quite helpful for me and if you can make a minimal julia code which the error that would be excellent! :-)
