### ISSUE TITLE
Unexpected behavior indexing Variable with unlimited dimension with CartesianIndex and UnitRange

### ISSUE THREAD

**Issue by weech** [Alexander-Barth/NCDatasets.jl#23]
Ran across this edge case today. Let's say you have a Variable named `var` with 3 dimensions where the outermost dimension is unlimited. `var[CartesianIndex(1, 1), 2:end]` returns an empty vector, but `var[1, 1, 2:end]` does not. Also `var[CartesianIndex(1, 1), 2:nt]` where `nt` is the current length of the 3rd dimension behaves as expected. So there is something about the getindex method that gets called with a CartesianIndex and UnitRange with `end` that triggers this bug.

**Comment by Alexander-Barth** [comment]
Can you provide me a minimum reproducible example of this error? You can for example use `ncgen` to create the code generating a small netcdf producing this error. Thanks!

**Comment by weech** [comment]
Hmm, it looks like this is a misunderstanding on my part on how Julia handles indexing. 
```Julia
using NCDatasets
ds = Dataset("filename.nc", "c");
ds.dim["lon"] = 5;
ds.dim["lat"] = 10;
ds.dim["time"] = Inf;

nctime = defVar(ds, "time", Int64, ("time",));
nctime.attrib["units"] = "days since 1900-01-01 00:00:00";
nctime.attrib["calendar"] = "standard";

ncvar = defVar(ds, "var", Int64, ("lon", "lat", "time"));

nt = 25;
nctime[1:nt] = 1:nt;
a = reshape(1:5*10*nt, 5, 10, nt);
ncvar[:] = a;
close(ds);

ds = Dataset("filename.nc");
start = 1;
all(a[CartesianIndex(1, 1), start:end] .== ds["var"][CartesianIndex(1, 1), start:end])
```
The final statement returns `true`, which means that the NCDatasets behavior is normal for Julia (even if it's unexpected and wrong).
However, I did find another bug. `ds["var"][CartesianIndex(1, 1), start:nt]` returns an array of `Array{Union{Missing, Float64},1}` even though var holds Int64.

**Comment by Alexander-Barth** [comment]
>  The final statement returns true, which means that the NCDatasets behavior is normal for Julia (even if it's unexpected and wrong).

I do not see why you have a problem with this behavior, but if really think it is wrong you can file an issue at https://github.com/JuliaLang/julia/issues
NCDatasets uses Julia's `AbstractArrays` who handles `CartesianIndex`.

`ds["var"][CartesianIndex(1, 1), start:nt]` returns now an `Array{Union{Missing, DateTime, Number, AbstractCFDateTime},1}` (version in master).  It is not more specific because the type depends on `units`, `scale_factor` and `add_offset` (who can change their value).  But the type of `data11[1]` is now Int64.

```
data11 = ds["var"][CartesianIndex(1, 1), start:end]
typeof(data11[1])
```
