### ISSUE TITLE
Dimension ordering

### ISSUE THREAD

**Issue by kpamnany** [Alexander-Barth/NCDatasets.jl#87]
**Describe the bug**

The dimensions of a variable seem to be in reverse order compared to what is seen by `ncdump` and other standard NetCDF viewers.

**To Reproduce**

```julia
Dataset("testdims.nc", "c") do ds
    ds["a"] = 1
    ds["b"] = 5
    defVar(ds, "ab", rand(1, 5), ("a", "b"))
end
```
Then:
```julia
ds = Dataset("testdims.nc", "r")
```
shows:
```
NCDataset: testdims.nc
Group: /

Dimensions
   a = 1
   b = 5

Variables
  ab   (1 × 5)
    Datatype:    Float64
    Dimensions:  a × b
```
But:
```bash
ncdump -v ab testdims.nc
```
shows:
```
netcdf testdims {
dimensions:
        a = 1 ;
        b = 5 ;
variables:
        double ab(b, a) ;

// global attributes:
                :_NCProperties = "version=1|netcdflibversion=4.6.1|hdf5libversion=1.10.1" ;
data:

 ab =
  0.23915721817469,
  0.0604798142888703,
  0.29052351895647,
  0.343953696965474,
  0.499267227025561 ;
}
```

**Expected behavior**

`ab` should be `double ab(a, b) ;` rather than `double ab(b, a)` as seen by `ncdump`.

**Environment**

 - CentOS Linux 7
 - Julia 1.3.1
 - NCDatasets version: 0.10.2

**Comment by Alexander-Barth** [comment]
This behavior is actually expected since Julia (as Fortran, octave, matlab, R...) is "column-major"
while C, C++, ... is "row-major".  `ncdump` as a C tool, happen to follow the "row-major" ordering.
(https://en.wikipedia.org/wiki/Row-_and_column-major_order ).

If you load the file in Octave or Fortran, you will see the same ordering as in NCDatasets.

You are not the first one confused by this:
https://www.unidata.ucar.edu/support/help/MailArchives/netcdf/msg02582.html

**Comment by kpamnany** [comment]
Thanks for clearing this up Alexander.
